"""Deterministically lower Fixture IR into marker-free backend seed sources."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class FixtureLoweringResult:
    sources: dict[str, str] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


class FixtureLowerer:
    def lower(
        self,
        fixture_ir: dict[str, Any],
        database_manifest: dict[str, Any],
    ) -> FixtureLoweringResult:
        errors: list[str] = []
        table_entities = {
            str(row.get("entity", ""))
            for row in database_manifest.get("tables", [])
            if isinstance(row, dict) and str(row.get("entity", ""))
        }
        sets = [
            row for row in fixture_ir.get("fixture_sets", []) if isinstance(row, dict)
        ]
        for fixture_set in sets:
            for row in fixture_set.get("rows", []):
                entity = str(row.get("entity_key", "")) if isinstance(row, dict) else ""
                if entity not in table_entities:
                    errors.append(f"ARC3410 FIXTURE_ENTITY_UNPLANNED: {entity!r}.")
        if errors:
            return FixtureLoweringResult(errors=list(dict.fromkeys(errors)))

        sources: dict[str, str] = {}
        imports: list[tuple[str, str]] = []
        sets_by_requirement: dict[str, list[dict[str, Any]]] = {}
        for fixture_set in sets:
            sets_by_requirement.setdefault(
                str(fixture_set.get("requirement_id", "")), []
            ).append(fixture_set)
        for requirement_id, requirement_sets in sorted(sets_by_requirement.items()):
            path = f"backend/src/fixtures/{_path_token(requirement_id)}.ts"
            symbol = f"fixtureSets_{_identifier_token(requirement_id)}"
            sources[path] = (
                "// Generated by ARC. Do not edit.\n"
                f"export const {symbol} = "
                f"{json.dumps(requirement_sets, ensure_ascii=False, indent=2)} as const;\n"
            )
            imports.append((symbol, f"./{_path_token(requirement_id)}.js"))

        sources["backend/src/fixtures/index.ts"] = _render_index(imports)
        sources["backend/init-db.mjs"] = _render_database_initializer(
            database_manifest.get("initialization", {}).get("statements", [])
        )
        return FixtureLoweringResult(sources=sources)


def fixture_source_paths(fixture_ir: dict[str, Any]) -> list[str]:
    paths = ["backend/src/fixtures/index.ts"]
    paths.extend(
        f"backend/src/fixtures/{_path_token(str(row.get('requirement_id', '')))}.ts"
        for row in fixture_ir.get("fixture_sets", [])
        if isinstance(row, dict)
    )
    return sorted(set(paths))


def _render_database_initializer(statements: list[str]) -> str:
    return "\n".join([
        'import Database from "better-sqlite3";',
        'import { mkdirSync, readFileSync } from "node:fs";',
        'import { dirname, resolve } from "node:path";',
        "",
        'const databaseUrl = (process.env.DATABASE_URL ?? "./data/app.db").trim();',
        'if (!databaseUrl) throw new Error("DATABASE_URL must not be empty.");',
        'if (databaseUrl !== ":memory:") mkdirSync(dirname(resolve(databaseUrl)), { recursive: true });',
        'const database = new Database(databaseUrl);',
        f'const statements = {json.dumps(statements, ensure_ascii=False)};',
        'const { fixture_sets: fixtureSets } = JSON.parse(readFileSync(new URL("../.arc/fixtures/fixture_ir.json", import.meta.url), "utf8"));',
        "try {",
        '  database.pragma("foreign_keys = OFF");',
        "  database.transaction(() => {",
        "    for (const statement of statements) database.exec(statement);",
        "    for (const fixtureSet of fixtureSets) {",
        "      for (const row of fixtureSet.rows) {",
        "        const entries = Object.entries(row.values).map(([field, value]) => [",
        '          field, typeof value === "boolean" ? Number(value) :',
        '            value !== null && typeof value === "object" ? JSON.stringify(value) : value,',
        "        ]);",
        "        const quote = name => '\"' + name.replaceAll('\"', '\"\"') + '\"';",
        "        const table = quote(row.entity_key);",
        '        if (!entries.length) {',
        '          if (!database.prepare("SELECT 1 FROM " + table + " LIMIT 1").get()) database.exec("INSERT INTO " + table + " DEFAULT VALUES");',
        '          continue;',
        '        }',
        '        const columns = entries.map(([field]) => quote(field)).join(", ");',
        '        const placeholders = entries.map(() => "?").join(", ");',
        "        const values = entries.map(([, value]) => value);",
        '        const lookup = entries.some(([field]) => field === "id") ? entries.filter(([field]) => field === "id") : entries;',
        '        const match = lookup.map(([field]) => quote(field) + " IS ?").join(" AND ");',
        '        database.prepare("INSERT INTO " + table + " (" + columns + ") SELECT " + placeholders + " WHERE NOT EXISTS (SELECT 1 FROM " + table + " WHERE " + match + ")").run(...values, ...lookup.map(([, value]) => value));',
        "      }",
        "    }",
        "  })();",
        "} finally {",
        "  database.close();",
        "}",
        "",
    ])


def _render_index(imports: list[tuple[str, str]]) -> str:
    lines = [
        "// Generated by ARC. Do not edit.",
        'import { sqliteDatabase } from "../db/client.js";',
        *[f'import {{ {symbol} }} from {json.dumps(specifier)};' for symbol, specifier in imports],
        "",
        "type FixtureValue = string | number | boolean | null | Readonly<Record<string, unknown>> | readonly unknown[];",
        "interface FixtureRow {",
        "  entity_key: string;",
        "  values: Readonly<Record<string, FixtureValue>>;",
        "}",
        "interface FixtureSet {",
        "  requirement_id: string;",
        "  rows: readonly FixtureRow[];",
        "}",
        "",
        "const fixtureSets: readonly FixtureSet[] = [",
        *[f"  ...{symbol}," for symbol, _ in imports],
        "] as const;",
        "",
        "const seed = sqliteDatabase.transaction((requirementId: string) => {",
        "    for (const fixtureSet of fixtureSets) {",
        "      if (fixtureSet.requirement_id !== requirementId) continue;",
        "      for (const row of fixtureSet.rows) {",
        "        const entries = Object.entries(row.values).map(([field, value]) => [",
        "          field,",
        "          typeof value === \"boolean\" ? Number(value) :",
        "            value !== null && typeof value === \"object\" ? JSON.stringify(value) : value,",
        "        ] as const);",
        '        const columns = entries.map(([field]) => `"${field.replaceAll(\'"\', \'""\')}"`).join(", ");',
        '        const placeholders = entries.map(() => "?").join(", ");',
        '        const table = `"${row.entity_key.replaceAll(\'"\', \'""\')}"`;',
        '        if (!entries.length) {',
        '          if (!sqliteDatabase.prepare(`SELECT 1 FROM ${table} LIMIT 1`).get()) sqliteDatabase.exec(`INSERT INTO ${table} DEFAULT VALUES`);',
        '          continue;',
        '        }',
        '        const lookup = entries.some(([field]) => field === "id") ? entries.filter(([field]) => field === "id") : entries;',
        "        const match = lookup.map(([field]) => '\"' + field.replaceAll('\"', '\"\"') + '\" IS ?').join(\" AND \");",
        '        const values = entries.map(([, value]) => value);',
        '        sqliteDatabase.prepare(`INSERT INTO ${table} (${columns}) SELECT ${placeholders} WHERE NOT EXISTS (SELECT 1 FROM ${table} WHERE ${match})`).run(...values, ...lookup.map(([, value]) => value));',
        "      }",
        "    }",
        "});",
        "",
        "export function seedFor(requirementId: string): void {",
        '  sqliteDatabase.pragma("foreign_keys = OFF");',
        "  try {",
        "    seed(requirementId);",
        "  } finally {",
        '    sqliteDatabase.pragma("foreign_keys = ON");',
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def _path_token(value: str) -> str:
    name = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "requirement"
    return f"{name}-{hashlib.sha256(value.encode('utf-8')).hexdigest()[:8]}"


def _identifier_token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    if not token or token[0].isdigit():
        token = f"requirement_{token}"
    return f"{token}_{hashlib.sha256(value.encode('utf-8')).hexdigest()[:8]}"
