"""Fixed runtime renderers for the database intermediate records."""

from __future__ import annotations

import ast
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from core.database_plan import compile_plan


JS_RUNTIME = r'''// Generated by ARC DATABASE_PREPARE. Change the JSON plan through requirement sync.
'use strict';
const PROGRAM = __PROGRAM__;
function run(db, sql) {
  return new Promise((resolve, reject) => db.run(sql, error => error ? reject(error) : resolve()));
}
function all(db, sql) {
  return new Promise((resolve, reject) => db.all(sql, (error, rows) => error ? reject(error) : resolve(rows)));
}
async function prepareDatabase(db) {
  await run(db, 'PRAGMA foreign_keys = ON');
  await run(db, 'BEGIN IMMEDIATE');
  try {
    for (const table of PROGRAM.tables) {
      await run(db, table.create);
      const columns = await all(db, `PRAGMA table_info("${table.name}")`);
      for (const column of table.columns) {
        if (!columns.some(existing => existing.name === column.name)) {
          await run(db, table.add_columns[column.name]);
        }
      }
    }
    for (const sql of PROGRAM.indexes) await run(db, sql);
    for (const sql of PROGRAM.seeds) await run(db, sql);
    const violations = await all(db, 'PRAGMA foreign_key_check');
    if (violations.length) throw new Error('Database foreign key violations: ' + JSON.stringify(violations));
    await run(db, 'COMMIT');
  } catch (error) {
    await run(db, 'ROLLBACK');
    throw error;
  }
}
module.exports = { prepareDatabase };
'''


PY_RUNTIME = r'''# Generated by ARC DATABASE_PREPARE. Change records through requirement sync.
import json
import os
import sqlite3
from pathlib import Path

PROGRAM = json.loads(__PROGRAM_LITERAL__)

def prepare_database(connection):
    connection.execute("PRAGMA foreign_keys = ON")
    with connection:
        connection.execute("BEGIN IMMEDIATE")
        for table in PROGRAM["tables"]:
            connection.execute(table["create"])
            names = {row[1] for row in connection.execute('PRAGMA table_info("' + table["name"] + '")')}
            for column in table["columns"]:
                if column["name"] not in names:
                    connection.execute(table["add_columns"][column["name"]])
        for sql in PROGRAM["indexes"] + PROGRAM["seeds"]:
            connection.execute(sql)
        if connection.execute("PRAGMA foreign_key_check").fetchall():
            raise RuntimeError("Database contains foreign key violations")

def connect_database(db_path=None):
    db_path = db_path or os.environ.get("ARC_DB_FILE") or os.environ.get("DATABASE_FILE") or "database.db"
    if db_path != ":memory:":
        Path(db_path).resolve().parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(db_path)
    try:
        prepare_database(connection)
    except Exception:
        connection.close()
        raise
    return connection

if __name__ == "__main__":
    connect_database().close()
'''


JAVA_RUNTIME = r'''// Generated by ARC DATABASE_PREPARE. Do not edit.
package __PACKAGE__.database;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.util.HashSet;
import java.util.Set;

/** Shared persistence boundary; getWritableDatabase prepares schema and default data. */
public final class ArcDatabase extends SQLiteOpenHelper {
    private final Context context;
    public ArcDatabase(Context context) {
        this(context, "database.db");
    }
    public ArcDatabase(Context context, String databaseName) {
        super(context.getApplicationContext(), databaseName, null, 1);
        this.context = context.getApplicationContext();
    }
    @Override public void onConfigure(SQLiteDatabase db) { db.setForeignKeyConstraintsEnabled(true); }
    @Override public void onCreate(SQLiteDatabase db) { }
    @Override public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) { }
    @Override public void onOpen(SQLiteDatabase db) {
        super.onOpen(db);
        db.beginTransaction();
        try (InputStream input = context.getAssets().open("arc_database.json")) {
            ByteArrayOutputStream buffer = new ByteArrayOutputStream();
            byte[] bytes = new byte[4096];
            int count;
            while ((count = input.read(bytes)) != -1) buffer.write(bytes, 0, count);
            JSONObject program = new JSONObject(buffer.toString("UTF-8"));
            JSONArray tables = program.getJSONArray("tables");
            for (int i = 0; i < tables.length(); i++) {
                JSONObject table = tables.getJSONObject(i);
                db.execSQL(table.getString("create"));
                Set<String> names = new HashSet<>();
                try (Cursor cursor = db.rawQuery("PRAGMA table_info(\"" + table.getString("name") + "\")", null)) {
                    while (cursor.moveToNext()) names.add(cursor.getString(1));
                }
                JSONArray columns = table.getJSONArray("columns");
                for (int j = 0; j < columns.length(); j++) {
                    String name = columns.getJSONObject(j).getString("name");
                    if (!names.contains(name)) db.execSQL(table.getJSONObject("add_columns").getString(name));
                }
            }
            for (String key : new String[]{"indexes", "seeds"}) {
                JSONArray statements = program.getJSONArray(key);
                for (int i = 0; i < statements.length(); i++) db.execSQL(statements.getString(i));
            }
            try (Cursor cursor = db.rawQuery("PRAGMA foreign_key_check", null)) {
                if (cursor.moveToFirst()) throw new IllegalStateException("Database foreign key violations");
            }
            db.setTransactionSuccessful();
        } catch (Exception error) {
            throw new IllegalStateException("ARC database initialization failed", error);
        } finally { db.endTransaction(); }
    }
}
'''


def render_files(plan: dict[str, Any], app_type: str, android_package: str) -> dict[str, str]:
    program = compile_plan(plan)
    encoded = json.dumps(program, ensure_ascii=True, sort_keys=True, indent=2)
    if app_type == "web":
        return {"backend/src/database/arc_database.js": JS_RUNTIME.replace("__PROGRAM__", encoded)}
    if app_type == "cli":
        return {"app/arc_database.py": PY_RUNTIME.replace("__PROGRAM_LITERAL__", repr(encoded))}
    if app_type == "android":
        return {
            "app/src/main/assets/arc_database.json": encoded + "\n",
            f"app/src/main/java/{android_package.replace('.', '/')}/database/ArcDatabase.java":
                JAVA_RUNTIME.replace("__PACKAGE__", android_package),
        }
    raise ValueError(f"No database renderer for app_type={app_type}")


def write_generated_files(workspace: Path, files: dict[str, str]) -> None:
    """Write only compiler-owned paths, checking symlink escapes before every mutation."""
    root = workspace.resolve()
    for relative, content in files.items():
        path = root / relative
        if not path.resolve().is_relative_to(root):
            raise ValueError(f"Database generated path escapes workspace: {relative}")
        path.parent.mkdir(parents=True, exist_ok=True)
        # Use an adjacent temporary file so interruption never leaves a half-written module.
        temporary = path.with_name(path.name + ".arc-tmp")
        if temporary.is_symlink():
            raise ValueError(f"Database temporary path must not be a symlink: {relative}")
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(path)


def web_init_hook(workspace: Path) -> dict[str, str]:
    """Integrate with the existing scaffold without replacing its connection lifecycle."""
    path = workspace / "backend/src/database/init_db.js"
    if not path.resolve().is_relative_to(workspace.resolve()):
        raise ValueError("Database initialization path escapes workspace")
    if not path.is_file():
        raise ValueError("Web database preparation requires backend/src/database/init_db.js")
    source = path.read_text(encoding="utf-8")
    hook = "    await require('./arc_database').prepareDatabase(database); // ARC_DATABASE_PREPARE"
    if "// ARC_DATABASE_PREPARE" in source:
        if source.count(hook) != 1:
            raise ValueError("The compiler-owned database bootstrap hook was modified")
        return {}
    anchor = "    await runStatement(database, 'PRAGMA foreign_keys = ON;');"
    if source.count(anchor) != 1:
        raise ValueError("Existing DB initializer does not expose the ARC scaffold bootstrap anchor; adapt init_db.js before compiling")
    return {"backend/src/database/init_db.js": source.replace(anchor, anchor + "\n" + hook, 1)}


WEB_VERIFY_RUNTIME = """// Generated by ARC DATABASE_PREPARE. Do not edit.
'use strict';
const { initializeDatabase, closeDb, getDbPath } = require('./init_db');

async function verifyRuntime() {
  try {
    await initializeDatabase();
    console.log('Prepared SQLite database: ' + getDbPath());
  } finally {
    await closeDb();
  }
}

if (require.main === module) {
  verifyRuntime().catch(error => {
    console.error('Database initialization failed:', error);
    process.exitCode = 1;
  });
}

module.exports = { verifyRuntime };
"""


def fixed_web_runtime(workspace: Path) -> dict[str, str]:
    """Materialize fixed scaffold code; migrate known legacy code, reject customization."""
    template = Path(__file__).resolve().parents[1] / "arc-template/templates/web-react-express/backend/src/database"
    hook = "    await require('./arc_database').prepareDatabase(database); // ARC_DATABASE_PREPARE"
    result: dict[str, str] = {}
    for name in ("init_db.js", "db_runtime.js", "index.js", "seed_db.js", "test_harness.js", "prepare_e2e.js", "verify_runtime.js"):
        relative = "backend/src/database/" + name
        target = workspace / relative
        if target.is_symlink() or not target.resolve().is_relative_to(workspace.resolve()):
            raise ValueError(f"Unsafe fixed database runtime path: {relative}")
        # The verifier belongs to the compiler, not the application template.
        # Generate it on every preparation, including resumes of older workspaces.
        expected = WEB_VERIFY_RUNTIME if name == "verify_runtime.js" else (template / name).read_text(encoding="utf-8")
        if target.exists():
            original = target.read_text(encoding="utf-8")
            normalized = original.replace(hook + "\n", "") if name == "init_db.js" else original
            comparison = expected
            if name == "init_db.js":
                pattern = r"    /\*\*\n     \* Guide model instructions:\n.*?     \*/"
                replacement = "    // Fixed connection lifecycle. Schema and seeds come from ARC's JSON compiler."
                # Normalize both sides: the current template may still contain
                # the legacy guidance block. Keep materialized output unchanged.
                normalized = re.sub(pattern, replacement, normalized, count=1, flags=re.DOTALL)
                comparison = re.sub(pattern, replacement, expected, count=1, flags=re.DOTALL)
                # Known legacy initializers cached a Promise resolving to undefined.
                # Accept only that missing return; all other customizations still fail.
                promise_end = r"\n(?:    return database;\n)?  \}\)\(\);"
                fixed_end = "\n    return database;\n  })();"
                normalized = re.sub(promise_end, fixed_end, normalized, count=1)
                comparison = re.sub(promise_end, fixed_end, comparison, count=1)
            if name == "seed_db.js":
                legacy = re.sub(r"    /\*\*\n     \* Guide model instructions:\n.*?     \*/", "", original, count=1, flags=re.DOTALL)
                skeleton = """const { closeDb } = require('./init_db');
const { withTransaction } = require('./db_runtime');
async function seedDatabase() {
  return withTransaction(async ({ run, get, all, exec }) => {
    void run; void get; void all; void exec;
  });
}
"""
                prefix, separator, suffix = legacy.partition("if (require.main === module)")
                expected_suffix = expected.partition("if (require.main === module)")[2]
                if (separator and re.sub(r"\s+", "", prefix) == re.sub(r"\s+", "", skeleton)
                        and suffix == expected_suffix):
                    normalized = expected
            if normalized != comparison:
                raise ValueError(f"Database runtime differs from the fixed scaffold: {relative}; migrate custom code explicitly, not through node TDD")
        if name == "init_db.js":
            anchor = "    await runStatement(database, 'PRAGMA foreign_keys = ON;');"
            expected = expected.replace(anchor, anchor + "\n" + hook, 1)
        result[relative] = expected
    return result


def runtime_bootstrap_hook(workspace: Path, app_type: str, android_package: str) -> dict[str, str]:
    if app_type == "web":
        return fixed_web_runtime(workspace)
    if app_type == "cli":
        relative = "app/__main__.py"
        path = workspace / relative
        if not path.resolve().is_relative_to(workspace.resolve()):
            raise ValueError("CLI database bootstrap path escapes workspace")
        if not path.is_file():
            raise ValueError("CLI bootstrap requires app/__main__.py")
        source = path.read_text(encoding="utf-8")
        hook = "from .arc_database import connect_database as _arc_connect\n_arc_connect().close()  # ARC_DATABASE_PREPARE\n"
        if "# ARC_DATABASE_PREPARE" in source:
            if source.count(hook) != 1:
                raise ValueError("The compiler-owned CLI database bootstrap hook was modified")
            return {}
        # Place before application imports/entrypoint but after module docstring and future imports.
        module = ast.parse(source)
        offset = 0
        for index, statement in enumerate(module.body):
            if (index == 0 and isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Constant)
                    and isinstance(statement.value.value, str)) or (
                    isinstance(statement, ast.ImportFrom) and statement.module == "__future__"):
                offset = statement.end_lineno or statement.lineno
            else:
                break
        lines = source.splitlines(keepends=True)
        return {relative: "".join(lines[:offset]) + "\n" + hook + "\n" + "".join(lines[offset:])}
    if app_type == "android":
        manifest = ET.parse(workspace / "app/src/main/AndroidManifest.xml")
        application = manifest.getroot().find("application")
        name = application.get("{http://schemas.android.com/apk/res/android}name", "") if application is not None else ""
        if not name:
            raise ValueError("Android database bootstrap requires a manifest-declared Java Application class")
        full_name = android_package + name if name.startswith(".") else name if "." in name else android_package + "." + name
        relative = "app/src/main/java/" + full_name.replace(".", "/") + ".java"
        path = workspace / relative
        if not path.resolve().is_relative_to(workspace.resolve()):
            raise ValueError("Android database bootstrap path escapes workspace")
        if not path.is_file():
            raise ValueError("Android database bootstrap requires a Java Application source file")
        source = path.read_text(encoding="utf-8")
        hook = f"        try ({android_package}.database.ArcDatabase arcDb = new {android_package}.database.ArcDatabase(this)) {{ arcDb.getWritableDatabase(); }} // ARC_DATABASE_PREPARE"
        if "// ARC_DATABASE_PREPARE" in source:
            if source.count(hook) != 1:
                raise ValueError("The compiler-owned Android database bootstrap hook was modified")
            return {}
        pattern = r"super\.onCreate\(\);"
        if len(re.findall(pattern, source)) != 1:
            raise ValueError("Android Application source must have one super.onCreate() bootstrap anchor")
        return {relative: re.sub(pattern, lambda match: match.group(0) + "\n" + hook, source, count=1)}
    raise ValueError(f"Unknown database bootstrap application type: {app_type}")
